/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuconverção;

import java.awt.RenderingHints.Key;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import modelo.Construtora;
import static modelo.Construtora.converteOctalParaHexadecimal;
import modelo.modeloHistorico;

/**
 *
 * @author lucas
 */
public class painel extends javax.swing.JFrame {
Construtora construir = new Construtora();
String visor;
modeloHistorico xhistorico;
List<String> listHistorico = new ArrayList<String>();
/**
     * Creates new form painel
     */
    public painel() {
        initComponents();
        xhistorico = new modeloHistorico();
        //setExtendedState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtVisor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBt0 = new javax.swing.JButton();
        jBt1 = new javax.swing.JButton();
        jBt2 = new javax.swing.JButton();
        jBt3 = new javax.swing.JButton();
        jBt4 = new javax.swing.JButton();
        jBt5 = new javax.swing.JButton();
        jBt6 = new javax.swing.JButton();
        jBt7 = new javax.swing.JButton();
        jBtConverta = new javax.swing.JButton();
        jBtLimpar = new javax.swing.JButton();
        jbnHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Octal 1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(20, 20));
        getContentPane().setLayout(null);

        jTxtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtVisor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTxtVisor.setMinimumSize(new java.awt.Dimension(600, 200));
        jTxtVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtVisorActionPerformed(evt);
            }
        });
        jTxtVisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtVisorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtVisorKeyTyped(evt);
            }
        });
        getContentPane().add(jTxtVisor);
        jTxtVisor.setBounds(50, 40, 420, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("  Digite um valor em base OCtal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 370, 20);

        jBt0.setText("0");
        jBt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt0);
        jBt0.setBounds(50, 110, 80, 30);

        jBt1.setText("1");
        jBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt1);
        jBt1.setBounds(160, 110, 80, 30);

        jBt2.setText("2");
        jBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt2);
        jBt2.setBounds(290, 110, 80, 30);

        jBt3.setText("3");
        jBt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt3);
        jBt3.setBounds(390, 110, 80, 30);

        jBt4.setText("4");
        jBt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt4);
        jBt4.setBounds(50, 150, 80, 30);

        jBt5.setText("5");
        jBt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt5);
        jBt5.setBounds(160, 150, 80, 30);

        jBt6.setText("6");
        jBt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt6);
        jBt6.setBounds(290, 150, 80, 30);

        jBt7.setText("7");
        jBt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt7);
        jBt7.setBounds(390, 150, 80, 30);

        jBtConverta.setText("Converter");
        jBtConverta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConvertaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtConverta);
        jBtConverta.setBounds(20, 200, 150, 40);

        jBtLimpar.setText("Limpar");
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jBtLimpar);
        jBtLimpar.setBounds(190, 200, 150, 40);

        jbnHistorico.setText("Histórico");
        jbnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(jbnHistorico);
        jbnHistorico.setBounds(360, 200, 130, 40);

        setSize(new java.awt.Dimension(529, 303));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtVisorActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jTxtVisorActionPerformed

    private void jBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt1ActionPerformed
        // TODO add your handling code here:
        jTxtVisor.setText(jTxtVisor.getText()+1);
    }//GEN-LAST:event_jBt1ActionPerformed

    private void jBt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt0ActionPerformed
       
        jTxtVisor.setText(jTxtVisor.getText()+0);    
 
    }//GEN-LAST:event_jBt0ActionPerformed

    private void jBt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt5ActionPerformed
        // TODO add your handling code here:
        jTxtVisor.setText(jTxtVisor.getText()+5);
    }//GEN-LAST:event_jBt5ActionPerformed

    private void jBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt2ActionPerformed
        // TODO add your handling code here:
        jTxtVisor.setText(jTxtVisor.getText()+2);
    }//GEN-LAST:event_jBt2ActionPerformed

    private void jBt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt3ActionPerformed
       jTxtVisor.setText(jTxtVisor.getText()+3);
    }//GEN-LAST:event_jBt3ActionPerformed

    private void jBt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt4ActionPerformed
        jTxtVisor.setText(jTxtVisor.getText()+4);
    }//GEN-LAST:event_jBt4ActionPerformed

    private void jBt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt6ActionPerformed
       jTxtVisor.setText(jTxtVisor.getText()+6);
    }//GEN-LAST:event_jBt6ActionPerformed

    private void jBt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt7ActionPerformed
      jTxtVisor.setText(jTxtVisor.getText()+7);
    }//GEN-LAST:event_jBt7ActionPerformed

    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed
        // TODO add your handling code here:
        jTxtVisor.setText("");
    }//GEN-LAST:event_jBtLimparActionPerformed

    private void jTxtVisorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtVisorKeyPressed
        

    }//GEN-LAST:event_jTxtVisorKeyPressed

    private void jTxtVisorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtVisorKeyTyped
        String caracteres="01234567";
if(!caracteres.contains(evt.getKeyChar()+"")){
evt.consume();}
    }//GEN-LAST:event_jTxtVisorKeyTyped

    private void jBtConvertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConvertaActionPerformed
    String valor = jTxtVisor.getText();    
    jTxtVisor.setText(construir.converteOctalParaHexadecimal(valor));
    String testeVetor[][] = {{valor,jTxtVisor.getText()}};    
    xhistorico.setvHistorico(testeVetor);    
listHistorico.add(xhistorico.toString());
    }//GEN-LAST:event_jBtConvertaActionPerformed


    private void jbnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnHistoricoActionPerformed
 jfHistorico telaHistorico = new jfHistorico();
        telaHistorico.AdicionarHistorico(listHistorico);
	telaHistorico.show();
        
    }//GEN-LAST:event_jbnHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new painel().setVisible(true);
         
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt0;
    private javax.swing.JButton jBt1;
    private javax.swing.JButton jBt2;
    private javax.swing.JButton jBt3;
    private javax.swing.JButton jBt4;
    private javax.swing.JButton jBt5;
    private javax.swing.JButton jBt6;
    private javax.swing.JButton jBt7;
    private javax.swing.JButton jBtConverta;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtVisor;
    private javax.swing.JButton jbnHistorico;
    // End of variables declaration//GEN-END:variables
}
